[project]
name = "anki-dtz-goethe-b1-de-pl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "genanki>=0.13.1",
    "google-genai>=1.25.0",
    "pydantic>=2.11.7",
]
